version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL="postgresql://neondb_owner:npg_ZHWz7bFXhw2m@ep-fancy-silence-a10da67s-pooler.ap-southeast-1.aws.neon.tech/pixoraDataBase?sslmode=require&channel_binding=require"
      
    volumes:
      - ./server/uploads:/app/uploads
    # Commented out database URL, user should provide Neon connection string
    # - DATABASE_URL=postgresql://user:password@neon-host/dbname
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server
